### PR TITLE
Updated README.md with node shields badge/download

### PR DESCRIPTION
**Pull request by patrickaloia**
You may want it to link to the most current node releases still, but I tried to match it with the node version you have in the package.json

### CODE REVIEW

**Comment by anistark** [comment]
Thanks @patrickaloia for this. 
👍 
However, the idea was to update the `package.json` file or add some other file so that the badge can pick that up automatically. Wouldn't be feasible to keep updating the readme each time a version update happens.

**Comment by patrickaloia** [comment]
Ah, that makes more sense. I'll look into that!

**Comment by anistark** [comment]
Thanks @patrickaloia. However, for the time being, merging this since this is the only workaround available.

**Comment by patrickaloia** [comment]
Sounds good!

**Pull request merged**
